#!/usr/bin/env python3
"""
Gemini Code Review Script
Analyzes PR changes using Google Gemini API and posts review comments.
"""

import os
import sys
from google import genai
from github import Github, Auth

def get_pr_diff(repo, pr_number):
    """Fetch the PR diff from GitHub."""
    pr = repo.get_pull(pr_number)
    files = pr.get_files()

    # Exclude files that don't need AI code review to save context tokens
    EXCLUDE_EXT = ('.lock', '.svg', '.png', '.jpg', '.jpeg', '.gif', '.min.js', '.min.css', '.map')
    EXCLUDE_FILES = ('package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'poetry.lock', 'Pipfile.lock')

    diff_content = []
    for file in files:
        filename = file.filename
        if filename.endswith(EXCLUDE_EXT) or any(filename.endswith(f) for f in EXCLUDE_FILES):
            continue

        diff_content.append(f"--- a/{filename}")
        diff_content.append(f"+++ b/{filename}")
        if file.patch:
            diff_content.append(file.patch)
        diff_content.append("") # Empty line to separate files

    return "\n".join(diff_content), pr

def review_with_gemini(diff_content, api_key):
    """Send the diff to Gemini for code review."""
    
    client = genai.Client(api_key=api_key)
    
    # Priority: Flash (fast/efficient) -> Pro (stronger reasoning) -> Legacy
    #model_names = ['gemini-2.5-flash', 'gemini-2.5-flash-lite', ]
    if os.environ.get('GEMINI_MODEL'):
        model_names = [os.environ.get('GEMINI_MODEL')]
    else:
        model_names = ['gemini-2.5-flash', 'gemini-2.5-flash-lite']
    
    prompt = f"""Review these pull request changes. Provide constructive feedback focusing on:
1. Potential Bugs (logic, edge cases)
2. Security Vulnerabilities
3. Performance Issues
4. Code Quality & Best Practices

Format:
- Overall summary
- Specific issues (filename and lines)
- Positive highlights

Changes:
{diff_content}"""

    for name in model_names:
        try:
            print(f"Attempting to generate review with model: {name}")
            response = client.models.generate_content(
                model=name,
                contents=prompt
            )
            return response.text
        except Exception as e:
            print(f"Warning: Failed with {name}: {e}")
            
    print("Error: Could not generate review with any Gemini models. Please check your API key and quota.", file=sys.stderr)
    sys.exit(1)

def post_review_comment(pr, review_text):
    """Post the review as a comment on the PR."""
    comment_body = f"""## ♊ Gemini Code Review

{review_text}

---
*This review was automatically generated by Google Gemini AI.*
"""
    pr.create_issue_comment(comment_body)

def main():
    """Main function to orchestrate the code review process."""
    try:
        # Get environment variables with stripping
        github_token = os.environ.get('GITHUB_TOKEN', '').strip()
        gemini_key = os.environ.get('GEMINI_API_KEY', '').strip()
        pr_number = int(os.environ.get('PR_NUMBER', '0'))
        repo_name = os.environ.get('REPO_NAME', '').strip()

        # Debug logging (masked)
        print(f"Debug: PR_NUMBER={pr_number}")
        print(f"Debug: REPO_NAME={repo_name}")
        if gemini_key:
            print(f"Debug: GEMINI_API_KEY found (starts with: {gemini_key[:4]}...)")
        else:
            print("Debug: GEMINI_API_KEY not found")

        if not github_token or not gemini_key or not repo_name or pr_number == 0:
            print("Error: Missing required environment variables. Please check your GitHub Repository Secrets (GEMINI_API_KEY).", file=sys.stderr)
            sys.exit(1)

        # Initialize GitHub client
        auth = Auth.Token(github_token)
        g = Github(auth=auth)
        repo = g.get_repo(repo_name)

        print(f"Fetching PR #{pr_number} from {repo_name}...")
        diff_content, pr = get_pr_diff(repo, pr_number)

        if not diff_content.strip():
            print("No changes found in PR. Skipping review.")
            return

        print("Sending changes to Gemini for review...")
        review = review_with_gemini(diff_content, gemini_key)

        print("Posting review comment to PR...")
        post_review_comment(pr, review)

        print("✓ Code review completed successfully!")

    except Exception as e:
        print(f"Error during code review: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()