services:
  test-base:
    build:
      context: ..
      dockerfile: docker/Dockerfile.base
    command: pytest -m "not gpu and not synthcity" tests/ -v --tb=short

  test-gpu:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: pytest tests/ -v --tb=short

  test-synthcity:
    build:
      context: ..
      dockerfile: docker/Dockerfile.synthcity
    command: pytest -m "synthcity" tests/ -v --tb=short
